[package]
name = "kursovaya"
version = "0.1.0"
authors = ["Vladislav <vavus44375@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.2"
rand = { version = "0.8.3", features=["small_rng"] }
